#----------------------------------------------------------------
# Travis-CI configuration for Bioconductor packages
#
# REFERENCES:
# * Travis CI: https://travis-ci.org/
# * tutorial: https://docs.travis-ci.com/user/languages/r
# * see also: https://blog.rstudio.org/2016/03/09/r-on-travis-ci/
# * covr: https://github.com/jimhester/covr
# * Coveralls: https://coveralls.io/
#
# Validate your .travis.yml file at http://lint.travis-ci.org/
#----------------------------------------------------------------
language: r
cache: packages

# R versions to be tested on
r:
  - bioc-release
  - bioc-devel
  
# dependency for gsl>copula>zinbwave>splatter
addons:
  apt:
    packages:
      - libgsl-dev

## Turn this to true before submission to CRAN/Bioconductor
warnings_are_errors: true

r_build_args: "--no-build-vignettes"
r_check_args: "--no-vignettes"

notifications:
  email:
    on_success: change
    on_failure: change

## Code coverage
r_packages:
  - covr

## BiocCheck
bioc_packages:
  - BiocCheck

## install and upgrade dependencies
install:
 - R -e 'if ("devtools" %in% rownames(installed.packages())) update.packages(oldPkgs = "devtools", ask = FALSE) else install.packages("devtools")'
 - R -e 'setRepositories(ind = 1:2); devtools::install(dependencies = TRUE, upgrade = TRUE)'

after_success:
  - Rscript -e 'covr::coveralls()'
  - R CMD BiocCheck .
